version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=weather-app;userid=admin;password=admin123!;;
    restart: always
    networks:
      - mynetwork
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123!
      MYSQL_DATABASE: weather-app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
     - "3306:3306"
    volumes:
       - dbdata:/var/lib/mysql
    networks:
      - mynetwork

volumes:
    dbdata: 
        driver: local
networks:
  mynetwork: